"""empty message

Revision ID: 038c3d1913a0
Revises: cef56df72e33
Create Date: 2022-11-03 02:11:29.214834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038c3d1913a0'
down_revision = 'cef56df72e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_grupo_muscular',
    sa.Column('grupomuscularid', sa.Integer(), nullable=False),
    sa.Column('grupo_nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('grupomuscularid')
    )
    op.create_table('t_musculos',
    sa.Column('musculoid', sa.Integer(), nullable=False),
    sa.Column('grupomuscularid', sa.Integer(), nullable=False),
    sa.Column('musculo', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('musculoid', 'grupomuscularid')
    )
    op.create_table('t_profile',
    sa.Column('profileid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('altura', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('masa_muscular', sa.Integer(), nullable=False),
    sa.Column('grasa_corporal', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('profileid', 'userid')
    )
    op.create_table('t_rutina_predeterminada',
    sa.Column('rutinapredeterminadaid', sa.Integer(), nullable=False),
    sa.Column('nombrerutina', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('rutinapredeterminadaid')
    )
    op.create_table('t_tracker',
    sa.Column('trackerid', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('rutina_del_dia', sa.Integer(), nullable=False),
    sa.Column('calorias_quemadas', sa.Float(), nullable=False),
    sa.Column('distancia_recorrida', sa.Float(), nullable=False),
    sa.Column('pasos_diarios', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('trackerid', 'userID', 'rutina_del_dia')
    )
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ejercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musculoid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['musculoid'], ['t_musculos.musculoid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_rutina_del_dia',
    sa.Column('rutinadeldiaid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('rutinadeldiaid')
    )
    op.create_table('t_rutina_libre',
    sa.Column('rutinalibreid', sa.Integer(), nullable=False),
    sa.Column('musculoid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['musculoid'], ['t_musculos.musculoid'], ),
    sa.PrimaryKeyConstraint('rutinalibreid')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('t_rutina_libre')
    op.drop_table('t_rutina_del_dia')
    op.drop_table('ejercicios')
    op.drop_table('t_user')
    op.drop_table('t_tracker')
    op.drop_table('t_rutina_predeterminada')
    op.drop_table('t_profile')
    op.drop_table('t_musculos')
    op.drop_table('t_grupo_muscular')
    # ### end Alembic commands ###
